BOSS_NAMES = [
    "Nightmare (Solo)",
    "Phosani's Nightmare",
    "Vardorvis",
    "Duke Succellus",
    "The Whisperer",
    "Leviathan",
    "Vardorvis (Awakened)",
    "Duke Succellus (Awakened)",
    "The Whisperer (Awakened)",
    "Leviathan (Awakened)",
    "Inferno",
    "Fight Caves",
    "The Gauntlet",
    "The Corrupted Gauntlet",
    "Zulrah",
    "Vorkath",
    "Grotesque Guardians",
    "Alchemical Hydra",
    "Phantom Muspah",
    "Hespori",
    "Mimic",
    "Hallowed Sepulchre (overall)",
]
