tasks = [
    {
        "task_name": "any Revenant Weapon",
        "task_number": 1,
        "task_description": "You better hope your slayer block list is set up for the wildy because you are going to need that good rng. Get any one of the revenant weapons: Craw's Bow, Thammaron's Sceptre or Viggora's Chainmace",
        "task_points": 50,
        "task_challenge_name": "Upgrade your new wildy weapon",
        "task_challenge_description": "Get the matching upgrade for the revenant weapon",
        "task_challenge_points": 25,
        "image_link": "https://oldschool.runescape.wiki/images/Revenant_maledictus.png?73c48",
    },
    {
        "task_name": "a voidwaker piece",
        "task_number": 2,
        "task_description": "Did someone say 'I love getting ranged on by multi clans?' Set up your scout and get to killing those wildy bosses because you need to get any 1 of the voidwaker pieces",
        "task_points": 15,
        "task_challenge_name": "Complete one full voidwaker",
        "task_challenge_description": "Complete one full voidwaker",
        "task_challenge_points": 50,
        "image_link": "https://oldschool.runescape.wiki/images/Voidwaker_detail.png?01835",
    },
    {
        "task_name": "a revenant emblem worth 2m or more",
        "task_number": 3,
        "task_description": "Don't let the other teams know that you're headed to the revenant caves to get yourself an emblem worth 2m or more",
        "task_points": 15,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Ancient_emblem_detail.png?f448f",
    },
    {
        "task_name": "one pair of every slayer boot",
        "task_number": 4,
        "task_description": "This one is for the sneakerheads. Collect one of every boot dropped by slayer monsters: bronze through dragon.",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Dragon_boots_detail.png?35048",
    },
    {
        "task_name": "a pair of dark claws",
        "task_number": 5,
        "task_description": "Time to upgrade those normal flippers! It's about time you got the final piece to your 'purple outfit' you've been working on.",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Dark_claw_detail.png?878f6",
    },
    {
        "task_name": "A pair of granite boots",
        "task_number": 6,
        "task_description": "This is not a slayer task you want to skip. Grab your stabby boi and get to work on those wyverns!",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Granite_boots_detail.png?03de7",
    },
    {
        "task_name": "a bellator vestige",
        "task_number": 7,
        "task_description": "Did someone say worst drop mechanic from jamflex yet?",
        "task_points": 25,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Bellator_ring_detail.png?3616e",
    },
    {
        "task_name": "a ring of the gods",
        "task_number": 8,
        "task_description": "Best piece of inferno gear shoebin owns",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Ring_of_the_gods_detail.png?4a4e9",
    },
    {
        "task_name": "a tyrannical ring",
        "task_number": 9,
        "task_description": "Wait... who drops this one? Callisto? Venenatis? I don't even remember. Someone look it up.",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Tyrannical_ring_detail.png?36d00",
    },
    {
        "task_name": "a treasonous ring",
        "task_number": 10,
        "task_description": "Wait... who drops this one? Callisto? Venenatis? I don't even remember. Someone look it up.",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Treasonous_ring_detail.png?859ba",
    },
    {
        "task_name": "a venator vestige",
        "task_number": 11,
        "task_description": "Did someone say worst drop mechanic from jamflex yet?",
        "task_points": 25,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Venator_ring_detail.png?5ca31",
    },
    {
        "task_name": "a seers ring",
        "task_number": 12,
        "task_description": "Quick, look up which dk drops this one!",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Seers_ring_detail.png?c8823",
    },
    {
        "task_name": "a magus vestige",
        "task_number": 13,
        "task_description": "I swear I'm 2/3. I swear I'm 2/3. I swear I'm 2/3. I swear I'm 2/3.",
        "task_points": 25,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Magus_ring_detail.png?7d63e",
    },
    {
        "task_name": "an archers ring",
        "task_number": 14,
        "task_description": "Maybe you can use a dragon axe or two. I'm also feeling a pet this trip.",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Archers_ring_detail.png?4eab1",
    },
    {
        "task_name": "a lightbearer",
        "task_number": 15,
        "task_description": "money 150s anyone?",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Lightbearer_detail.png?3576d",
    },
    {
        "task_name": "a berserker ring",
        "task_number": 16,
        "task_description": "It is 2010, you just got home from middle school, you got your juice box and pizza bagels. Time to kill some DKs for that glorious ring.",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Berserker_ring_detail.png?81f8b",
    },
    {
        "task_name": "a ultor vestige",
        "task_number": 17,
        "task_description": "Did someone say worst drop mechanic from jamflex yet?",
        "task_points": 25,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Ultor_ring_detail.png?784a8",
    },
    {
        "task_name": "a warriors ring",
        "task_number": 18,
        "task_description": "remember when this ring was useless?",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Warrior_ring_detail.png?4a4e9",
    },
    {
        "task_name": "a venator shard",
        "task_number": 19,
        "task_description": "That kinda looks like something I saw in unrot's moms nightstand...",
        "task_points": 10,
        "task_challenge_name": "Complete a Venator bow",
        "task_challenge_description": "Complete a Venator bow",
        "task_challenge_points": 50,
        "image_link": "https://oldschool.runescape.wiki/images/Phantom_Muspah_%28ranged%29.png?9cf6a",
    },
    {
        "task_name": "a piece of dragon stone armor",
        "task_number": 20,
        "task_description": "This is one ugly armor set but good thing you only need one piece!",
        "task_points": 5,
        "task_challenge_name": "Sike, Complete The dragonstone armor set",
        "task_challenge_description": "Complete the full dragonstone armor set",
        "task_challenge_points": 25,
        "image_link": "https://oldschool.runescape.wiki/images/Dragonstone_armour_equipped_male.png?74e8f",
    },
    {
        "task_name": "a zilyana unique",
        "task_number": 21,
        "task_description": "Remember to change that click through on the unicorn!",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Commander_Zilyana.png?c5eaa",
    },
    {
        "task_name": "one of the big fishes",
        "task_number": 22,
        "task_description": "Fishing enjoyers rejoice, you can make your team proud! Capture one of the big fishes: Bass, Swordfish, Shark, or Harpoonfish",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Big_shark_detail.png?e3794",
    },
    {
        "task_name": "a tempoross unique",
        "task_number": 23,
        "task_description": "Firefighting has never been so fun. Get any temporass unique. Soaked pages only counts if it is a drop of 25",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Tempoross_%28enraged%29.png?2075d",
    },
    {
        "task_name": "a full angler outfit",
        "task_number": 24,
        "task_description": "bro why did shoebin put this stupid minigame in here",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Angler%27s_outfit_equipped.png?cef02",
    },
    {
        "task_name": "a nightmare unique",
        "task_number": 25,
        "task_description": "Any nightmare unique that is not an egg. Might as well get those CAs while you are at it!",
        "task_points": 50,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/The_Nightmare.png?0128a",
    },
    {
        "task_name": "Steal a lantadyme or higher tier seed",
        "task_number": 26,
        "task_description": "We aren't in leagues anymore, there's no auto pickpocket here (but still, #TricksterGang)",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Master_Farmer.png?c21af",
    },
    {
        "task_name": "a pharaoh scepter",
        "task_number": 27,
        "task_description": "The master will be displeased when you yoink this. Who even is the master? I thought that mummy just ran the whole place",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Pharaoh%27s_sceptre_detail.png?164e0",
    },
    {
        "task_name": "a full rogues outfit",
        "task_number": 28,
        "task_description": "The original Hallowed Sepulchre. Can you do this without the plugin?",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Rogue_equipment_equipped_female.png?0c6f7",
    },
    {
        "task_name": "a nex unique",
        "task_number": 29,
        "task_description": "You either hate it or you love it. Do NOT double-die on the way back to reclaim your stuff.",
        "task_points": 50,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Nex.png?2a1b3",
    },
    {
        "task_name": "an inferno cape",
        "task_number": 30,
        "task_description": "Quick @shoebin for this one",
        "task_points": 5,
        "task_challenge_name": "Complete the inferno on mobile",
        "task_challenge_description": "Complete the inferno on mobile",
        "task_challenge_points": 10,
        "image_link": "https://oldschool.runescape.wiki/images/Infernal_cape_detail.png?03de7",
    },
    {
        "task_name": "a piece of the pyromancer outfit",
        "task_number": 31,
        "task_description": "The cold of the Wintertodt seeps into your bones. Public chat is probably best to be turned off here.",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Pyromancer_outfit_equipped_female.png?830a4",
    },
    {
        "task_name": "a Fire Cape",
        "task_number": 32,
        "task_description": "One of the sweatiest of all PvM challenges. Focus up as the waves get higher and higher and don't let your guard down.",
        "task_points": 5,
        "task_challenge_name": "Complete the fight caves on mobile",
        "task_challenge_description": "Complete the fight caves on mobile",
        "task_challenge_points": 5,
        "image_link": "https://oldschool.runescape.wiki/images/Fire_cape_detail.png?f1d0",
    },
    {
        "task_name": "a kree'arra Unique",
        "task_number": 33,
        "task_description": "Sound effect users HATE this place. Don't bring too many chinchompas.",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Kree%27arra.png?ba75c",
    },
    {
        "task_name": "an elven signet",
        "task_number": 34,
        "task_description": "'haha anyone wanna scout some crystal imps for me?' god prif is so laggy.",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Elven_signet_detail.png?e6a10",
    },
    {
        "task_name": "a zalcano unique",
        "task_number": 35,
        "task_description": "smolcano is an s-tier pet",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Zalcano.png?6244d",
    },
    {
        "task_name": "a baronite mace from scratch",
        "task_number": 36,
        "task_description": "This is one cool area, I bet you are happy to hangout here!",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Barronite_mace_detail.png?9bbfe",
    },
    {
        "task_name": "a graardor unique",
        "task_number": 37,
        "task_description": "There is a garagedoor in osrs?",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/General_Graardor.png?4dd90",
    },
    {
        "task_name": "a piece of obsidian armor",
        "task_number": 38,
        "task_description": "Too bad the poison bug was fixed!",
        "task_points": 10,
        "task_challenge_name": "Complete the obsidian armor set",
        "task_challenge_description": "Get obisidian platebody, platelegs, and helmet",
        "task_challenge_points": 25,
        "image_link": "https://oldschool.runescape.wiki/images/Obsidian_armour_equipped_male.png?bd207",
    },
    {
        "task_name": "a GOTR unique",
        "task_number": 39,
        "task_description": "This is a dogshit minigame, if you get an lantern, I don't like you",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Rewards_Guardian.png?ea71b",
    },
    {
        "task_name": "a piece of evil chicken outfit",
        "task_number": 40,
        "task_description": "Check your kingdom! Or participate in Forestry... I hear that's a good method nowadays.",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Evil_chicken_outfit_equipped.png?5d24c",
    },
    {
        "task_name": "a k'ril tsutsaroth unique",
        "task_number": 41,
        "task_description": "KRILL TUTT-zee-roth. The boss that somehow everyone knows how to pronounce. (and NOBODY can get 'ardougne' right)",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/K%27ril_Tsutsaroth.png?73bda",
    },
    {
        "task_name": "Mask of Ranul",
        "task_number": 42,
        "task_description": "Another dead god?",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Mask_of_ranul_detail.png?4f67e",
    },
    {
        "task_name": "any pair of medium clue boots",
        "task_number": 43,
        "task_description": "please be the rangers, please be the rangers, please be... (any medium clue boots count: ranger, wizard, holy sandals, spiked manacles, or climbing boots (g))",
        "task_points": 15,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Ranger_boots_detail.png?e421a",
    },
    {
        "task_name": "a piece of justicar armor",
        "task_number": 44,
        "task_description": "No time for board checking! You didn't get world rec this time, get over it and pot again.",
        "task_points": 25,
        "task_challenge_name": "Morytania Only",
        "task_challenge_description": "Get the justicar drop while under Morytania Only conditions",
        "task_challenge_points": 25,
        "image_link": "https://oldschool.runescape.wiki/images/Justiciar_armour_equipped_male.png?17b57",
    },
    {
        "task_name": "a soulreaper axe piece",
        "task_number": 45,
        "task_description": "What is this axe even good for? Hopefully they buff it someday.",
        "task_points": 25,
        "task_challenge_name": "Complete the soul reaper axe",
        "task_challenge_description": "Complete the soul reaper axe",
        "task_challenge_points": 150,
        "image_link": "https://oldschool.runescape.wiki/images/Soulreaper_axe_detail.png?27b3b",
    },
    {
        "task_name": "a vorkath unique",
        "task_number": 46,
        "task_description": "Hopefully the line at vorky isn't long. Vorkath head does not count",
        "task_points": 25,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Vorkath.png?1ce3f",
    },
    {
        "task_name": "a brine sabre",
        "task_number": 47,
        "task_description": ":pog: sailing content. It's that funny item that is a lot rarer than it seems. I swear everyone goes 3x rate for it. Maybe you will.",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Brine_sabre_detail.png?1f853",
    },
    {
        "task_name": "a godsword shard",
        "task_number": 48,
        "task_description": "12 year old you would be so jealous if you got a godsword",
        "task_points": 5,
        "task_challenge_name": "Complete a godsword blade (minus hilt)",
        "task_challenge_description": "Complete a godsword blade (minus hilt)",
        "task_challenge_points": 15,
        "image_link": "https://oldschool.runescape.wiki/images/Godsword_blade_detail.png?0d1f4",
    },
    {
        "task_name": "a piece of masori armor",
        "task_number": 49,
        "task_description": "Everyone knows if you milk the reveal it triples your purple chance. 'Please be yellow'",
        "task_points": 25,
        "task_challenge_name": "f2p only",
        "task_challenge_description": "Get the drop while wearing only f2p gear",
        "task_challenge_points": 50,
        "image_link": "https://oldschool.runescape.wiki/images/Masori_armour_equipped_female.png?d7d2c",
    },
    {
        "task_name": "the bryophta essence",
        "task_number": 50,
        "task_description": "brb, googling what is the fastest way to get mossy keys...",
        "task_points": 25,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Bryophyta%27s_staff_%28uncharged%29_detail.png?7ef7e",
    },
    {
        "task_name": "a piece of barrows gear",
        "task_number": 51,
        "task_description": "End game circa 2007. Really takes you back to the simple times. Except they didn't have barrows tabs back then. Or orante pools.",
        "task_points": 5,
        "task_challenge_name": "Complete an entire barrows set",
        "task_challenge_description": "",
        "task_challenge_points": 50,
        "image_link": "https://oldschool.runescape.wiki/images/Chest_%28Barrows%29.png?9aff2",
    },
    {
        "task_name": "an occult necklace",
        "task_number": 52,
        "task_description": "Sell it before jamflex nerfs it! And don't fall for that trick of taking off your slayer helmet to the troll calling you bald.",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Occult_necklace_detail.png?08adc",
    },
    {
        "task_name": "the bloodshard twice",
        "task_number": 53,
        "task_description": "Will you thieve, or will you fight the bots and vennys for some afk spots?",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Blood_shard_detail.png?2fbc7",
    },
    {
        "task_name": "any champion scroll",
        "task_number": 54,
        "task_description": "Champion max cape when?",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Leon%27s_champion_scroll_detail.png?9b7ca",
    },
    {
        "task_name": "the giant club",
        "task_number": 55,
        "task_description": "You know what we need? A fire giant boss with fire keys... maybe they'll show that in the Winter Summit. Nope. Maybe 2025 then.",
        "task_points": 15,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Hill_giant_club_detail.png?53073",
    },
    {
        "task_name": "a gauntlet unique",
        "task_number": 56,
        "task_description": "Get yourself to the red prison and snag that enhanced! (armor, weapon, enhanced, pet all count)",
        "task_points": 15,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Crystalline_Hunllef.png?7737a",
    },
    {
        "task_name": "a piece of dagonhai",
        "task_number": 57,
        "task_description": "Make sure you check the upstairs of the ship for PKers. There's never anybody up there, but the one time you don't check you'll be sorry.",
        "task_points": 5,
        "task_challenge_name": "Complete the dagonhai set",
        "task_challenge_description": "",
        "task_challenge_points": 25,
        "image_link": "https://oldschool.runescape.wiki/images/Dagon%27hai_robes_equipped_male.png?f4a94",
    },
    {
        "task_name": "the gnome scarf",
        "task_number": 58,
        "task_description": "Peak fashionscape!s",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Gnome_scarf_detail.png?5e19c",
    },
    {
        "task_name": "one satchel of each color",
        "task_number": 59,
        "task_description": "Collect all 6 satchels: Black, Gold, Green, Plain, Red, and Rune",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Black_satchel_detail.png?3c71d",
    },
    {
        "task_name": "a cerb unique",
        "task_number": 60,
        "task_description": "Time to get your prims! Smouldering stone from normal hellhounds also counts.",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Cerberus.png?47f4c",
    },
    {
        "task_name": "a monkey tail",
        "task_number": 61,
        "task_description": "It's that rare drop you don't want to see.... Except you do, because it's bingo. So just do it. Go get it.",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Monkey_tail_detail.png?853b6",
    },
    {
        "task_name": "a kalphite queen head",
        "task_number": 62,
        "task_description": "Why do does she keep all those potato cacti? Tattered head does not count",
        "task_points": 15,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Kq_head_detail.png?4a8ca",
    },
    {
        "task_name": "a dragon pick",
        "task_number": 63,
        "task_description": "Grab an extra to leave in toa",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Dragon_pickaxe_detail.png?4f4ee",
    },
    {
        "task_name": "any piece of ancestral",
        "task_number": 64,
        "task_description": "!layout",
        "task_points": 25,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Ancestral_robes_equipped_female.png?91894",
    },
    {
        "task_name": "a zulrah unique",
        "task_number": 65,
        "task_description": "Commonly referred to as the 'money snake.' Except the GP/hour these days are very, very bad.. - oh look a bot with 30K kc.",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Zulrah_%28tanzanite%29.png?fd984",
    },
    {
        "task_name": "a kraken tentacle",
        "task_number": 66,
        "task_description": "I think I can still feel the suction cups on it. Eww.",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Kraken_tentacle_detail.png?e5f2a",
    },
    {
        "task_name": "a shaman mask",
        "task_number": 67,
        "task_description": "It shares the same bonuses as an iron full helm, but with an additional +1 Ranged attack bonus. Next time you see someone wearing an iron full helm, correct them by tellign them to wear this.",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Shaman_mask_detail.png?c8823",
    },
    {
        "task_name": "complete a skull sceptre from scratch",
        "task_number": 68,
        "task_description": "Did you know that the skull sceptre can autocast spells from the Arceuus spellbook? Now you do.",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Skull_sceptre_detail.png?ccd18",
    },
    {
        "task_name": "a strange lockpick",
        "task_number": 69,
        "task_description": "S tier skilling content",
        "task_points": 5,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Strange_old_lockpick_%28full%29_detail.png?1925a",
    },
    {
        "task_name": "a corp Unique",
        "task_number": 70,
        "task_description": "I heard someone using voidwaker! Only dwh specs!",
        "task_points": 50,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Corporeal_Beast.png?52ebb",
    },
    {
        "task_name": "a sriracha unique",
        "task_number": 71,
        "task_description": "Is that how you spell the name?",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Sarachnis.png?8f040",
    },
    {
        "task_name": "a mist battlestaff",
        "task_number": 72,
        "task_description": "That could have been an imbued heart...",
        "task_points": 10,
        "task_challenge_name": "",
        "task_challenge_description": "",
        "task_challenge_points": 0,
        "image_link": "https://oldschool.runescape.wiki/images/Mist_battlestaff_detail.png?e6004",
    },
]
