from enum import Enum


class PVMActivities(Enum):
    Nightmare_Solo = "Nightmare (Solo)"
    Phosanis_Nightmare = "Phosani's Nightmare"
    Vardorvis = "Vardorvis"
    Duke_Succellus = "Duke Succellus"
    The_Whisperer = "The Whisperer"
    Leviathan = "Leviathan"
    Vardorvis_Awakened = "Vardorvis (Awakened)"
    Duke_Succellus_Awakened = "Duke Succellus (Awakened)"
    The_Whisperer_Awakened = "The Whisperer (Awakened)"
    Leviathan_Awakened = "Leviathan (Awakened)"
    Inferno = "Inferno"
    Fight_Caves = "Fight Caves"
    The_Gauntlet = "The Gauntlet"
    The_Corrupted_Gauntlet = "The Corrupted Gauntlet"
    Zulrah = "Zulrah"
    Vorkath = "Vorkath"
    Grotesque_Guardians = "Grotesque Guardians"
    Alchemical_Hydra = "Alchemical Hydra"
    Phantom_Muspah = "Phantom Muspah"
    Hespori = "Hespori"
    Mimic = "Mimic"
    Hallowed_Sepulchre = "Hallowed Sepulchre (overall)"
    Theatre_of_Blood = "Theatre of Blood"
    Theatre_of_Blood_Hard_Mode = "Theatre of Blood: Hard Mode"
    Chambers_of_Xeric = "Chambers of Xeric"
    Chambers_of_Xeric_Challenge_Mode = "Chambers of Xeric: Challenge Mode"
    Tombs_of_Amascut_Expert_Mode = "Tombs of Amascut: Expert Mode"
