RAID_NAMES = [
    "Theatre of Blood (5-Man)",
    "Theatre of Blood (4-Man)",
    "Theatre of Blood 3-Man)",
    "Theatre of Blood (Duo)",
    "Theatre of Blood (Solo)",
    "Theatre of Blood: Hard Mode (5-Man)",
    "Theatre of Blood: Hard Mode (4-Man)",
    "Theatre of Blood: Hard Mode (3-Man)",
    "Theatre of Blood: Hard Mode (Duo)",
    "Theatre of Blood: Hard Mode (Solo)",
    "Chambers of Xeric (5-Man)",
    "Chambers of Xeric (3-Man)",
    "Chambers of Xeric (Duo)",
    "Chambers of Xeric (Solo)",
    "Chambers of Xeric: Challenge Mode (5-Man)",
    "Chambers of Xeric: Challenge Mode (3-Man)",
    "Chambers of Xeric: Challenge Mode (Duo)",
    "Chambers of Xeric: Challenge Mode (Solo)",
    "Tombs of Amascut: Expert Mode (8 Man)",
    "Tombs of Amascut: Expert Mode (5 Man)",
    "Tombs of Amascut: Expert Mode (Trio)",
    "Tombs of Amascut: Expert Mode (Duo)",
    "Tombs of Amascut: Expert Mode (Solo)",
    "Tombs of Amascut (Trio)",
    "Tombs of Amascut (Duo)",
    "Tombs of Amascut (Solo)",
]
