CDN_URLS = {
    "Theatre of Blood": "https://oldschool.runescape.wiki/images/thumb/Theatre_of_Blood_logo.png/250px-Theatre_of_Blood_logo.png?e6e68",
    "Theatre of Blood: Hard Mode": "https://oldschool.runescape.wiki/images/thumb/Sanguine_dust_detail.png/150px-Sanguine_dust_detail.png?831a8",
    "Chambers of Xeric": "https://oldschool.runescape.wiki/images/thumb/Great_Olm.png/300px-Great_Olm.png?f1081",
    "Chambers of Xeric: Challenge Mode": "https://oldschool.runescape.wiki/images/thumb/Metamorphic_dust_detail.png/150px-Metamorphic_dust_detail.png?d0e85",
    "Tombs of Amascut: Expert Mode": "https://oldschool.runescape.wiki/images/thumb/Tumeken%27s_Warden_%28level-544%29.png/250px-Tumeken%27s_Warden_%28level-544%29.png?7db9d",
    "Nightmare (Solo)": "https://oldschool.runescape.wiki/images/thumb/The_Nightmare.png/250px-The_Nightmare.png?0128a",
    "Phosani's Nightmare": "https://oldschool.runescape.wiki/images/thumb/Little_Parasite.png/250px-Little_Parasite.png?ad14b",
    "Inferno": "https://oldschool.runescape.wiki/images/thumb/TzKal-Zuk.png/270px-TzKal-Zuk.png?2d222",
    "Fight Caves": "https://oldschool.runescape.wiki/images/thumb/TzTok-Jad.png/280px-TzTok-Jad.png?87507",
    "Vardorvis": "https://oldschool.runescape.wiki/images/thumb/Vardorvis.png/200px-Vardorvis.png?48af8",
    "Duke Succellus": "https://oldschool.runescape.wiki/images/thumb/Baron_%28follower%29.png/280px-Baron_%28follower%29.png?79d46",
    "The Whisperer": "https://oldschool.runescape.wiki/images/thumb/The_Whisperer.png/120px-The_Whisperer.png?aedab",
    "Leviathan": "https://oldschool.runescape.wiki/images/thumb/The_Leviathan.png/280px-The_Leviathan.png?d588a",
    "Vardorvis (Awakened)": "https://oldschool.runescape.wiki/images/thumb/Vardorvis.png/200px-Vardorvis.png?48af8",
    "Duke Succellus (Awakened)": "https://oldschool.runescape.wiki/images/thumb/Baron_%28follower%29.png/280px-Baron_%28follower%29.png?79d46",
    "The Whisperer (Awakened)": "https://oldschool.runescape.wiki/images/thumb/The_Whisperer.png/120px-The_Whisperer.png?aedab",
    "Leviathan (Awakened)": "https://oldschool.runescape.wiki/images/thumb/The_Leviathan.png/280px-The_Leviathan.png?d588a",
    "The Gauntlet": "https://oldschool.runescape.wiki/images/thumb/Crystalline_Hunllef.png/280px-Crystalline_Hunllef.png?7737a",
    "The Corrupted Gauntlet": "https://oldschool.runescape.wiki/images/thumb/Corrupted_Hunllef.png/280px-Corrupted_Hunllef.png?0cd55",
    "Zulrah": "https://oldschool.runescape.wiki/images/thumb/Zulrah_%28serpentine%29.png/250px-Zulrah_%28serpentine%29.png?29a54",
    "Vorkath": "https://oldschool.runescape.wiki/images/thumb/Vorkath.png/280px-Vorkath.png?1ce3f",
    "Grotesque Guardians": "https://oldschool.runescape.wiki/images/thumb/Dusk.png/250px-Dusk.png?8af58",
    "Alchemical Hydra": "https://oldschool.runescape.wiki/images/thumb/Alchemical_Hydra_%28serpentine%29.png/272px-Alchemical_Hydra_%28serpentine%29.png?925dd",
    "Phantom Muspah": "https://oldschool.runescape.wiki/images/thumb/Phantom_Muspah_%28ranged%29.png/250px-Phantom_Muspah_%28ranged%29.png?9cf6a",
    "Hespori": "https://oldschool.runescape.wiki/images/thumb/Hespori.png/150px-Hespori.png?cd901",
    "Mimic": "https://oldschool.runescape.wiki/images/thumb/The_Mimic.png/250px-The_Mimic.png?b45f4",
    "Hallowed Sepulchre (overall)": "https://oldschool.runescape.wiki/images/thumb/Wizard_Statue_%28Ornate%2C_5%29.png/147px-Wizard_Statue_%28Ornate%2C_5%29.png?d407a",
}
