tiles = [
    {
        "Number": 0,
        "Title":"null",
        "QuirkyHeader": "something broke with the bot",
        "Description": "something broke with the bot",
        "Challenge": "something broke with the bot",
    },
    {
        "Number": 1,
        "Title":"Broken Zombie Axe",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Broken_zombie_axe_detail.png/120px-Broken_zombie_axe_detail.png?9768e",
        "QuirkyHeader": "",
        "Description": "Dropped by armoured zombies found within Zemouregal's Base.",
        "Challenge": "",
    },
    {
        "Number": 2,
        "Title":"Sulphur Blades",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Sulphur_blades_detail.png/130px-Sulphur_blades_detail.png?f6d50",
        "QuirkyHeader": "Obtained as a rare drop from sulphur nagua in Neypotzli.",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 3,
        "Title": "Mint Cake",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Mint_cake_detail.png/130px-Mint_cake_detail.png?783ac",
        "QuirkyHeader": "",
        "Description": "Obtained as a rare reward from Brambickle, Wingstone and Penwie in the Gnome Restaurant minigame.",
        "Challenge": "",
    },
    {
        "Number": 4,
        "Title": "3x Scurrius Spines",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Scurrius%27_spine_detail.png/130px-Scurrius%27_spine_detail.png?3f9d8",
        "QuirkyHeader": "",
        "Description": "An uncommon drop from Scurrius.",
        "Challenge": "",
    },
    {
        "Number": 5,
        "Title": "Crystal Grail",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Crystal_grail_detail.png/120px-Crystal_grail_detail.png?2315b",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 6,
        "Title": "Eternal Teleport Crystal",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Eternal_teleport_crystal_detail.png/100px-Eternal_teleport_crystal_detail.png?093d9",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 7,
        "Title": "Dragon Pickaxe OR Dragon 2H Sword",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Dragon_pickaxe_detail.png/140px-Dragon_pickaxe_detail.png?4f4ee",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 8,
        "Title": "5x Easy Clue Uniques",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Clue_scroll_%28easy%29_detail.png/150px-Clue_scroll_%28easy%29_detail.png?87067",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 9,
        "Title": "3x Fire Capes",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Fire_cape_detail.png/150px-Fire_cape_detail.png?f1d08",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 10,
        "Title": "Go back to tile 4",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Sandwich_lady.png/150px-Sandwich_lady.png?937a2",
        "QuirkyHeader": "DON'T IGNORE ME! *slaps you back to tile 4*",
        "Description": "Go back to tile 4. Sorry.",
        "Challenge": "",
    },
    {
        "Number": 11,
        "Title": "Wintertodt Unique",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Pyromancer_garb_detail.png/160px-Pyromancer_garb_detail.png?0e275",
        "QuirkyHeader": "",
        "Description": "No burnt pages",
        "Challenge": "",
    },
    {
        "Number": 12,
        "Title": "Any 4x Perilous Moon Pieces",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Eclipse_moon_armour_equipped_male.png/82px-Eclipse_moon_armour_equipped_male.png?ba742",
        "QuirkyHeader": "",
        "Description": "1 for each slot",
        "Challenge": "",
    },
    {
        "Number": 13,
        "Title": "1M Gathering XP",
        "ImageUrl":"https://oldschool.runescape.wiki/images/Stats_icon.png?1b467",
        "QuirkyHeader": "",
        "Description": "Farming doesn't count",
        "Challenge": "",
    },
    {
        "Number": 14,
        "Title": "Blood Shard",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Blood_shard_detail.png/100px-Blood_shard_detail.png?2fbc7",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 15,
        "Title": "Petal Garland OR Fox Whistle OR Golden Egg",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Petal_garland_detail.png/130px-Petal_garland_detail.png?4c134",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 16,
        "Title": "Zombie Champion Scroll",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Zombie_champion_scroll_detail.png/150px-Zombie_champion_scroll_detail.png?3964f",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 17,
        "Title": "Take the Quetzin to tile 23!",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Quetzin_%28follower%29.png/280px-Quetzin_%28follower%29.png?ca338",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 18,
        "Title": "Any Tempoross Unique",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Fish_barrel_detail.png/140px-Fish_barrel_detail.png?0e2a0",
        "QuirkyHeader": "",
        "Description": "25x Soaked Pages counts as well.",
        "Challenge": "",
    },
    {
        "Number": 19,
        "Title": "Shaman Mask",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Shaman_mask_detail.png/200px-Shaman_mask_detail.png?c8823",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 20,
        "Title": "3x KBD Heads",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Kbd_heads_detail.png/130px-Kbd_heads_detail.png?a6345",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 21,
        "Title": "Any (4) Barrows Equipment Pieces for Each Armor Slot",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Dharok%27s_armour_equipped_male.png/150px-Dharok%27s_armour_equipped_male.png?3d05c",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "Complete a full set from 1 brother",
    },
    {
        "Number": 22,
        "Title": "Any 2x Elder Chaos Robe Pieces",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Elder_chaos_druid_robes_equipped_female.png/150px-Elder_chaos_druid_robes_equipped_female.png?0316d",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 23,
        "Title": "Any Dye, Lantern, or Pet from GOTR",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Abyssal_lantern_%28maple_logs%29_detail.png/150px-Abyssal_lantern_%28maple_logs%29_detail.png?9a479",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 24,
        "Title": "Any Big Fish",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Big_shark_detail.png/130px-Big_shark_detail.png?e3794",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 25,
        "Title": "Any Seed From The Gauntlet",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Crystal_weapon_seed_detail.png/130px-Crystal_weapon_seed_detail.png?85ac9",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 26,
        "Title": "Blood Shard",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Blood_shard_detail.png/100px-Blood_shard_detail.png?2fbc7",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 27,
        "Title": "Any Ancient Rev Item Worth 2M+ or Weapon Roll",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Ancient_statuette_detail.png/150px-Ancient_statuette_detail.png?63bac",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 28,
        "Title": "TOB Purple",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Monumental_chest_%28player%27s_unique%2C_closed%29.png/280px-Monumental_chest_%28player%27s_unique%2C_closed%29.png?02929",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 29,
        "Title": "KQ Head",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Kq_head_detail.png/120px-Kq_head_detail.png?4a8ca",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 30,
        "Title": "Golden Tench",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Golden_tench_detail.png/130px-Golden_tench_detail.png?27700",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 31,
        "Title": "Pharaoh's sceptre",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Pharaoh%27s_sceptre_detail.png/150px-Pharaoh%27s_sceptre_detail.png?164e0",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 32,
        "Title": "5x Medium Clue Uniques",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Clue_scroll_%28medium%29_detail.png/150px-Clue_scroll_%28medium%29_detail.png?87067",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 33,
        "Title": "Kraken Tentacle",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Kraken_tentacle_detail.png/130px-Kraken_tentacle_detail.png?e5f2a",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 34,
        "Title": "Complete a Wilderness Ward from scratch",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Malediction_ward_detail.png/130px-Malediction_ward_detail.png?c708e",
        "QuirkyHeader": "Receive shards 1, 2, and 3 for either the Odium or Malediction Ward.",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 35,
        "Title": "Any ToA Unique",
        "ImageUrl": "https://oldschool.runescape.wiki/images/thumb/Lightbearer_detail.png/120px-Lightbearer_detail.png?3576d",
        "QuirkyHeader": "Gems and Thread count in this one. Kits, transmogs, shrouds, and cache of runes do not",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 36,
        "Title": "Any piece of the Guild hunter Outfit",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Guild_hunter_top_detail.png/130px-Guild_hunter_top_detail.png?be5ad",
        "QuirkyHeader": "",
        "Description": "Quetzin pet or Huntsman Kit will also complete this task.",
        "Challenge": "",
    },
    {
        "Number": 37,
        "Title": "2x Venator Shards",
        "ImageUrl": "https://oldschool.runescape.wiki/images/thumb/Venator_shard_detail.png/130px-Venator_shard_detail.png?3ad3e",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 38,
        "Title": "Strange Old Lockpick",
        "ImageUrl": "https://oldschool.runescape.wiki/images/thumb/Strange_old_lockpick_%28full%29_detail.png/120px-Strange_old_lockpick_%28full%29_detail.png?1925a",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 39,
        "Title": "Curved Bone",
        "ImageUrl": "https://oldschool.runescape.wiki/images/thumb/Curved_bone_detail.png/180px-Curved_bone_detail.png?2315b",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 40,
        "Title": "Take the Fairy Ring to tile 47!",
        "ImageUrl": "https://oldschool.runescape.wiki/images/thumb/Fairy_ring.png/200px-Fairy_ring.png?2ebb4",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 41,
        "Title": "Mask of Ranul",
        "ImageUrl": "https://oldschool.runescape.wiki/images/thumb/Mask_of_ranul_detail.png/150px-Mask_of_ranul_detail.png?4f67e",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 42,
        "Title": "Dragon Pickaxe",
        "ImageUrl": "https://oldschool.runescape.wiki/images/thumb/Dragon_pickaxe_detail.png/140px-Dragon_pickaxe_detail.png?4f4ee",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 43,
        "Title": "2M Gathering XP",
        "ImageUrl":"https://oldschool.runescape.wiki/images/Stats_icon.png?1b467",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 44,
        "Title": "Any CoX Purple",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Dexterous_prayer_scroll_detail.png/150px-Dexterous_prayer_scroll_detail.png?d6a6b",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 45,
        "Title": "3x Vorkath Heads",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Vorkath%27s_head_detail.png/130px-Vorkath%27s_head_detail.png?d5b97",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "Receive a Dragonbone Necklace",
    },
    {
        "Number": 46,
        "Title": "2x Unsired",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Unsired_detail.png/200px-Unsired_detail.png?36d00",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 47,
        "Title": "Amulet of Eternal Glory",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Amulet_of_eternal_glory_detail.png/120px-Amulet_of_eternal_glory_detail.png?34ecf",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 48,
        "Title": "Any Sunfire Fanatic Armor Piece",
        "ImageUrl":"https://oldschool.runescape.wiki/images/Sunfire_fanatic_helm_chathead.png?57ad9",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 49,
        "Title": "Last Man Standing",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Last_Man_Standing_logo.png/100px-Last_Man_Standing_logo.png?1e913",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 50,
        "Title": "Any Bandos Armor Piece",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Bandos_chestplate_detail.png/100px-Bandos_chestplate_detail.png?98028",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 51,
        "Title": "Any Nex Unique",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Zaryte_vambraces_detail.png/130px-Zaryte_vambraces_detail.png?fdfe1",
        "QuirkyHeader": "",
        "Description": "No, Nihil Shards do not count.",
        "Challenge": "",
    },
    {
        "Number": 52,
        "Title": "Deathless 500 TOA",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Cursed_phalanx_detail.png/150px-Cursed_phalanx_detail.png?8957f",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 53,
        "Title": "2x Cerberus Crystals",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Primordial_crystal_detail.png/140px-Primordial_crystal_detail.png?9c62f",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 54,
        "Title": "Any Armadyl Armor Piece",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Armadyl_helmet_detail.png/100px-Armadyl_helmet_detail.png?8793d",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 55,
        "Title": "2x TOA Purples",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Osmumten%27s_fang_detail.png/150px-Osmumten%27s_fang_detail.png?b88ec",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 56,
        "Title": "5x Hard Clue Uniques",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Clue_scroll_%28hard%29_detail.png/150px-Clue_scroll_%28hard%29_detail.png?11ee4",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 57,
        "Title": "Infernal Cape",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Infernal_cape_detail.png/150px-Infernal_cape_detail.png?03de7",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "Complete the Speedrunner and Floor is Lava CAs in the same run",
    },
    {
        "Number": 58,
        "Title": "Any Nightmare Unique",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Nightmare_staff_detail.png/160px-Nightmare_staff_detail.png?51fcd",
        "QuirkyHeader": "",
        "Description": "No Slepey Tablet. Parasitic Egg counts",
        "Challenge": "",
    },
    {
        "Number": 59,
        "Title": "Any Saradomin Weapon",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Saradomin_sword_detail.png/140px-Saradomin_sword_detail.png?5539e",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 60,
        "Title": "Occult Necklace",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Occult_necklace_detail.png/125px-Occult_necklace_detail.png?08adc",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 61,
        "Title": "Melee 4 Jads Combat Achievement",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/JalTok-Jad.png/280px-JalTok-Jad.png?7e369",
        "QuirkyHeader": "",
        "Description": "Turn on task repeats.",
        "Challenge": "",
    },
    {
        "Number": 62,
        "Title": "Arcane Prayer Scroll",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Arcane_prayer_scroll_detail.png/160px-Arcane_prayer_scroll_detail.png?54108",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 63,
        "Title": "Take the Hot Air Balloon to Tile 69!",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Air_balloon.png/199px-Air_balloon.png?11f02",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 64,
        "Title": "Any 2 Hydra Pre-rolls",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Hydra%27s_eye_detail.png/130px-Hydra%27s_eye_detail.png?6adc5",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 65,
        "Title": "Holy Elixir OR 3 Spirit Shields",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Holy_elixir_detail.png/90px-Holy_elixir_detail.png?65f9f",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 66,
        "Title": "4:00 Nightmare Speed (With Bingo OR Clan Members ONLY)",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/The_Nightmare.png/250px-The_Nightmare.png?0128a",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 67,
        "Title": "Any Zamorak Weapon",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Zamorakian_hasta_detail.png/150px-Zamorakian_hasta_detail.png?0470b",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 68,
        "Title": "Any Virtus Piece OR 10 Awakener's Orbs",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Virtus_robe_top_detail.png/150px-Virtus_robe_top_detail.png?b2b4a",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 69,
        "Title": "150 Invo 8-man TOA Deathless (With Bingo OR Clan Members ONLY)",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Tumeken%27s_Warden_%28level-544%29.png/250px-Tumeken%27s_Warden_%28level-544%29.png?7db9d",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "Same rules, but GM time",
    },
    {
        "Number": 70,
        "Title": "Dark Bow",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Dark_bow_detail.png/150px-Dark_bow_detail.png?71f6b",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 71,
        "Title": "Any 2x ToB Purples",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Sanguinesti_staff_%28uncharged%29_detail.png/180px-Sanguinesti_staff_%28uncharged%29_detail.png?6c90d",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 72,
        "Title": "Any Nex Unique",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Torva_full_helm_%28damaged%29_detail.png/130px-Torva_full_helm_%28damaged%29_detail.png?ecb1b",
        "QuirkyHeader": "",
        "Description": "No, Nihil Shards do not count.",
        "Challenge": "",
    },
    {
        "Number": 73,
        "Title": "2x Quivers",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Dizana%27s_quiver_%28uncharged%29_detail.png/150px-Dizana%27s_quiver_%28uncharged%29_detail.png?f6c23",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 74,
        "Title": "Any 2x Seeds from The Gauntlet",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Crystal_armour_seed_detail.png/120px-Crystal_armour_seed_detail.png?fa149",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 75,
        "Title": "3x Blood Shards",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Blood_shard_detail.png/100px-Blood_shard_detail.png?2fbc7",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 76,
        "Title": "Any 3x Zulrah Uniques",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Zulrah_%28serpentine%29.png/250px-Zulrah_%28serpentine%29.png?29a54",
        "QuirkyHeader": "",
        "Description": "Either Mutagen will insta-complete the tile. Zulrah Scales/Teleports do not count as a unique.",
        "Challenge": "",
    },
    {
        "Number": 77,
        "Title": "Budget Setup CA",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Tzkal_slayer_helmet_detail.png/120px-Tzkal_slayer_helmet_detail.png?6796d",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 78,
        "Title": "Phantom Muspah Manipulator",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Tzkal_slayer_helmet_detail.png/120px-Tzkal_slayer_helmet_detail.png?6796d",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 79,
        "Title": "You lost connection and died. Back to tile 73...",
        "ImageUrl":"https://oldschool.runescape.wiki/images/Skull_%28status%29_icon.png?fa6d8",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 80,
        "Title": "Feather Hunter CA",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Tzkal_slayer_helmet_detail.png/120px-Tzkal_slayer_helmet_detail.png?6796d",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 81,
        "Title": "Egniol Diet 2 CA",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Tzkal_slayer_helmet_detail.png/120px-Tzkal_slayer_helmet_detail.png?6796d",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 82,
        "Title": "No Time for a Drink CA",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Tzkal_slayer_helmet_detail.png/120px-Tzkal_slayer_helmet_detail.png?6796d",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 83,
        "Title": "Any 2x CoX Purples (No scrolls)",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Ancestral_robe_top_detail.png/150px-Ancestral_robe_top_detail.png?d12d2",
        "QuirkyHeader": "",
        "Description": "No Dex/Arcane scrolls",
        "Challenge": "",
    },
    {
        "Number": 84,
        "Title": "Lord of the Rings (All 4 DKs Rings)",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Berserker_ring_detail.png/150px-Berserker_ring_detail.png?81f8b",
        "QuirkyHeader": "",
        "Description": "1 of each Berserker, Warrior, Seers, and Archers Ring",
        "Challenge": "",
    },
    {
        "Number": 85,
        "Title": "5x Venator Shards OR 10x Ancient Icons",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Venator_shard_detail.png/130px-Venator_shard_detail.png?3ad3e",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 86,
        "Title": "Any 2x ToB Purples (No Avernic)",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Justiciar_legguards_detail.png/180px-Justiciar_legguards_detail.png?b297a",
        "QuirkyHeader": "",
        "Description": "No Avernic",
        "Challenge": "",
    },
    {
        "Number": 87,
        "Title": "5x Master Clue Uniques",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Clue_scroll_%28master%29_detail.png/150px-Clue_scroll_%28master%29_detail.png?f3c22",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 88,
        "Title": "Any Zalcano Unique",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Zalcano_shard_detail.png/150px-Zalcano_shard_detail.png?f52af",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 89,
        "Title": "Any 2x ToA Purples (No Lightbearer/Fang)",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Masori_body_detail.png/150px-Masori_body_detail.png?3576d",
        "QuirkyHeader": "",
        "Description": "No Lightbearer/Fang",
        "Challenge": "",
    },
    {
        "Number": 90,
        "Title": "Voidwaker From Scratch",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Voidwaker_detail.png/150px-Voidwaker_detail.png?01835",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 91,
        "Title": "Enhanced Crystal Weapon Seed",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Enhanced_crystal_weapon_seed_detail.png/130px-Enhanced_crystal_weapon_seed_detail.png?48996",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 92,
        "Title": "Any 3x CoX Prayer Scrolls",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Arcane_prayer_scroll_detail.png/160px-Arcane_prayer_scroll_detail.png?54108",
        "QuirkyHeader": "",
        "Description": "No, Torn Prayer scrolls don't count",
        "Challenge": "",
    },
    {
        "Number": 93,
        "Title": "3x Chromium Ingots OR Any Axe Piece",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Chromium_ingot_detail.png/130px-Chromium_ingot_detail.png?b410d",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "Receive any vestige",
    },
    {
        "Number": 94,
        "Title": "Any 5x Elite Clue Uniques",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Clue_scroll_%28elite%29_detail.png/150px-Clue_scroll_%28elite%29_detail.png?87067",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 95,
        "Title": "Complete any Godsword from scratch",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Bandos_godsword_detail.png/130px-Bandos_godsword_detail.png?2250a",
        "QuirkyHeader": "",
        "Description": "Any GWD Pet will auto-complete the tile. Godsword Shard 1, 2, AND 3. Any hilt.",
        "Challenge": "",
    },
    {
        "Number": 96,
        "Title": "3x Lightbearer(s) OR Fang(s)",
        "ImageUrl":"",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 97,
        "Title": "Any Jar",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Jar_of_spirits_detail.png/90px-Jar_of_spirits_detail.png?e6cf8",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 98,
        "Title": "CM Kit or Dust",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Twisted_ancestral_colour_kit_detail.png/170px-Twisted_ancestral_colour_kit_detail.png?d72c4",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 99,
        "Title": "HMT Kit or Dust",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Sanguine_ornament_kit_detail.png/120px-Sanguine_ornament_kit_detail.png?939b9",
        "QuirkyHeader": "",
        "Description": "",
        "Challenge": "",
    },
    {
        "Number": 100,
        "Title": "Tonalztics of Ralos OR 5 Echo Crystals",
        "ImageUrl":"https://oldschool.runescape.wiki/images/thumb/Tonalztics_of_ralos_%28uncharged%29_detail.png/150px-Tonalztics_of_ralos_%28uncharged%29_detail.png?32e17",
        "QuirkyHeader": "",
        "Description": "MUST be completed to win",
        "Challenge": "",
    }
]