BINGO_TILES = [
    {
        "Number": 1,
        "Name": "Broken zombie axe",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Zombie_axe_detail.png/120px-Zombie_axe_detail.png?be691",
        "CompletionCounter": 1,
    },
    {
        "Number": 2,
        "Name": "Sulphur blades",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Sulphur_blades_detail.png/130px-Sulphur_blades_detail.png?f6d50",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 3,
        "Name": "Mint cake",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Mint_cake_detail.png/130px-Mint_cake_detail.png?783ac",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 4,
        "Name": "(3) Scurius spines",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Scurrius%27_spine_detail.png/130px-Scurrius%27_spine_detail.png?3f9d8",
        "CompletionCounter": 3,
        "Challenge": "",
    },
    {
        "Number": 5,
        "Name": "Crystal Grail",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Crystal_grail_detail.png/120px-Crystal_grail_detail.png?2315b",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 6,
        "Name": "Enhanced teleport seed",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Enhanced_crystal_teleport_seed_detail.png/120px-Enhanced_crystal_teleport_seed_detail.png?84d93",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 7,
        "Name": "Dragon Pickaxe or D2H",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Dragon_pickaxe_detail.png/140px-Dragon_pickaxe_detail.png?4f4ee",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 8,
        "Name": "(5) Easy clue uniques (Not shared rewards log)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Clue_scroll_%28easy%29_detail.png/150px-Clue_scroll_%28easy%29_detail.png?87067",
        "CompletionCounter": 5,
        "Challenge": "",
    },
    {
        "Number": 9,
        "Name": "(3) Firecapes",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Fire_cape_detail.png/150px-Fire_cape_detail.png?f1d08",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 10,
        "Name": "GO BACK TO TILE 4",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Sandwich_lady.png/150px-Sandwich_lady.png?937a2",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 11,
        "Name": "Wintertodt unique. (No burnt pages)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Phoenix_%28follower%29.png/250px-Phoenix_%28follower%29.png?f6800",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 12,
        "Name": "Any (4) Perilous Moon equipment pieces (1 for each slot)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Eclipse_atlatl_detail.png/130px-Eclipse_atlatl_detail.png?8f887",
        "CompletionCounter": 4,
        "Challenge": "",
    },
    {
        "Number": 13,
        "Name": "1M exp in a gathering skill (not farming)",
        "Image": "https://oldschool.runescape.wiki/images/Stats_icon.png?1b467",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 14,
        "Name": "Blood Shard",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Blood_shard_detail.png/100px-Blood_shard_detail.png?2fbc7",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 15,
        "Name": "Petal garland, Fox whistle or golden egg",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Petal_garland_detail.png/130px-Petal_garland_detail.png?4c134",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 16,
        "Name": "Zombie champion scroll",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Zombie_champion_scroll_detail.png/150px-Zombie_champion_scroll_detail.png?3964f",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 17,
        "Name": "Take the Quetzin to tile 23!",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Quetzin_%28follower%29.png/280px-Quetzin_%28follower%29.png?ca338",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 18,
        "Name": "Any tempeross unique. (25x Soaked pages count. No Spirit flakes/normal roll pages)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Tempoross.png/300px-Tempoross.png?12042",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 19,
        "Name": "Shaman Mask",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Shaman_mask_detail.png/200px-Shaman_mask_detail.png?c8823",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 20,
        "Name": "(3) KBD Heads",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Kbd_heads_detail.png/130px-Kbd_heads_detail.png?a6345",
        "CompletionCounter": 3,
        "Challenge": "",
    },
    {
        "Number": 21,
        "Name": "Any (4) Barrows equipment pieces for each armor slot",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Dharok%27s_armour_equipped_male.png/150px-Dharok%27s_armour_equipped_male.png?3d05c",
        "CompletionCounter": 4,
        "Challenge": "Complete a full set from 1 brother",
    },
    {
        "Number": 22,
        "Name": "Any (2) Elder chaos robe pieces",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Elder_chaos_top_detail.png/180px-Elder_chaos_top_detail.png?19a96",
        "CompletionCounter": 2,
        "Challenge": "",
    },
    {
        "Number": 23,
        "Name": "Any Dye, Lantern, or pet from GOTR",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Abyssal_lantern_%28purple_logs%29_detail.png/150px-Abyssal_lantern_%28purple_logs%29_detail.png?9a479",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 24,
        "Name": "Any big fish",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Big_shark_detail.png/130px-Big_shark_detail.png?e3794",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 25,
        "Name": "Any seed from The Gauntlet",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Crystal_weapon_seed_detail.png/130px-Crystal_weapon_seed_detail.png?85ac9",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 26,
        "Name": "Blood Shard",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Blood_shard_detail.png/100px-Blood_shard_detail.png?2fbc7",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 27,
        "Name": "Any Rev emblem 2M+ or weapon roll. (avarice, mace, sceptre, bow)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Ancient_medallion_detail.png/150px-Ancient_medallion_detail.png?f448f",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 28,
        "Name": "Any TOB Purple",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Monumental_chest_%28player%27s_unique%2C_closed%29.png/280px-Monumental_chest_%28player%27s_unique%2C_closed%29.png?02929",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 29,
        "Name": "KQ Head",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Kq_head_detail.png/120px-Kq_head_detail.png?4a8ca",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 30,
        "Name": "Golden Tench",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Golden_tench_detail.png/130px-Golden_tench_detail.png?27700",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 31,
        "Name": "Pharaohs sceptre",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Pharaoh%27s_sceptre_%28uncharged%29_detail.png/150px-Pharaoh%27s_sceptre_%28uncharged%29_detail.png?e35e8",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 32,
        "Name": "(5) Medium clue uniques (not shared rewards log)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Clue_scroll_%28medium%29_detail.png/150px-Clue_scroll_%28medium%29_detail.png?87067",
        "CompletionCounter": 5,
        "Challenge": "",
    },
    {
        "Number": 33,
        "Name": "Kraken tentacle",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Kraken_tentacle_detail.png/130px-Kraken_tentacle_detail.png?e5f2a",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 34,
        "Name": "Complete a wildy ward from scratch (1 of each piece to the same ward)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Malediction_shard_2_detail.png/150px-Malediction_shard_2_detail.png?fe68e",
        "CompletionCounter": 3,
        "Challenge": "",
    },
    {
        "Number": 35,
        "Name": "Any TOA unique (Gems/Thread included)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Chest_%28Tombs_of_Amascut%2C_open%29.png/250px-Chest_%28Tombs_of_Amascut%2C_open%29.png?a0d1e",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 36,
        "Name": "Any Guild hunter armor piece, huntsman kit, or quetzal pet",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Guild_hunter_top_detail.png/130px-Guild_hunter_top_detail.png?be5ad",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 37,
        "Name": "(2) Venator shards",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Venator_shard_detail.png/130px-Venator_shard_detail.png?3ad3e",
        "CompletionCounter": 2,
        "Challenge": "",
    },
    {
        "Number": 38,
        "Name": "Strange old lockpick",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Strange_old_lockpick_%28full%29_detail.png/120px-Strange_old_lockpick_%28full%29_detail.png?1925a",
        "CompletionCounter": 1,
        "Challenge": "Ring of Endurance",
    },
    {
        "Number": 39,
        "Name": "Curved bone",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Curved_bone_detail.png/180px-Curved_bone_detail.png?2315b",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 40,
        "Name": "Take the fairy ring to tile 47!",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Fairy_ring.png/200px-Fairy_ring.png?2ebb4",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 41,
        "Name": "Mask of Ranul",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Mask_of_ranul_detail.png/150px-Mask_of_ranul_detail.png?4f67e",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 42,
        "Name": "Any (2) Dragon pickaxes or D2H",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Dragon_2h_sword_detail.png/120px-Dragon_2h_sword_detail.png?6ed9d",
        "CompletionCounter": 2,
        "Challenge": "",
    },
    {
        "Number": 43,
        "Name": "2M exp in a buyable skill",
        "Image": "https://oldschool.runescape.wiki/images/Stats_icon.png?1b467",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 44,
        "Name": "Any COX purple",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Arcane_prayer_scroll_detail.png/160px-Arcane_prayer_scroll_detail.png?54108",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 45,
        "Name": "(3) Vorkath Heads",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Vorkath%27s_head_detail.png/130px-Vorkath%27s_head_detail.png?d5b97",
        "CompletionCounter": 3,
        "Challenge": "Dragonbone necklace",
    },
    {
        "Number": 46,
        "Name": "(2) Unsireds",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Unsired_detail.png/200px-Unsired_detail.png?36d00",
        "CompletionCounter": 2,
        "Challenge": "",
    },
    {
        "Number": 47,
        "Name": "Amulet of Eternal Glory",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Amulet_of_eternal_glory_detail.png/120px-Amulet_of_eternal_glory_detail.png?34ecf",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 48,
        "Name": "Any Sunfire fanatic armor piece",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Sunfire_fanatic_helm_detail.png/150px-Sunfire_fanatic_helm_detail.png?b8ba8",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 49,
        "Name": "Win (5) games of LMS",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Last_Man_Standing_logo.png/100px-Last_Man_Standing_logo.png?1e913",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 50,
        "Name": "Bandos Armor piece",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Bandos_chestplate_detail.png/100px-Bandos_chestplate_detail.png?98028",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 51,
        "Name": "Any Nex Unique (not shards)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Zaryte_vambraces_detail.png/130px-Zaryte_vambraces_detail.png?fdfe1",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 52,
        "Name": "Deathless 500 TOA",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Cursed_phalanx_detail.png/150px-Cursed_phalanx_detail.png?8957f",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 53,
        "Name": "(2) Cerberus Crystals",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Primordial_crystal_detail.png/140px-Primordial_crystal_detail.png?9c62f",
        "CompletionCounter": 2,
        "Challenge": "",
    },
    {
        "Number": 54,
        "Name": "Any Armadyl Armor piece",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Armadyl_chestplate_detail.png/100px-Armadyl_chestplate_detail.png?78ba5",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 55,
        "Name": "(2) TOA purples",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Osmumten%27s_fang_detail.png/150px-Osmumten%27s_fang_detail.png?b88ec",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 56,
        "Name": "(5) Hard clue uniques (not shared rewards log)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Clue_scroll_%28hard%29_detail.png/150px-Clue_scroll_%28hard%29_detail.png?11ee4",
        "CompletionCounter": 5,
        "Challenge": "",
    },
    {
        "Number": 57,
        "Name": "Infernal cape",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Infernal_cape_detail.png/150px-Infernal_cape_detail.png?03de7",
        "CompletionCounter": 1,
        "Challenge": "No dig + speedrunner CA in one run",
    },
    {
        "Number": 58,
        "Name": "Any NM unique (not slepey tablet)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Parasitic_egg_detail.png/100px-Parasitic_egg_detail.png?e786a",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 59,
        "Name": "Any Saradomin weapon (from Commander Zilyana)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Saradomin_sword_detail.png/140px-Saradomin_sword_detail.png?5539e",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 60,
        "Name": "Occult Necklace",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Occult_necklace_detail.png/125px-Occult_necklace_detail.png?08adc",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 61,
        "Name": "Melee 4 jads CA",
        "Image": "https://oldschool.runescape.wiki/images/thumb/JalTok-Jad.png/280px-JalTok-Jad.png?7e369",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 62,
        "Name": "(2) COX purples",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Twisted_buckler_detail.png/130px-Twisted_buckler_detail.png?75ade",
        "CompletionCounter": 2,
        "Challenge": "",
    },
    {
        "Number": 63,
        "Name": "Take the hot air balloon to tile 69!",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Air_balloon.png/199px-Air_balloon.png?11f02",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 64,
        "Name": "Any (2) Hydra pre-rolls",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Hydra%27s_eye_detail.png/130px-Hydra%27s_eye_detail.png?6adc5",
        "CompletionCounter": 2,
        "Challenge": "",
    },
    {
        "Number": 65,
        "Name": "(3) Spirit Shields OR Holy Elixir",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Spirit_shield_detail.png/120px-Spirit_shield_detail.png?3524f",
        "CompletionCounter": 3,
        "Challenge": "",
    },
    {
        "Number": 66,
        "Name": "4:00 NM speed as all members in Kitty/bingo",
        "Image": "https://oldschool.runescape.wiki/images/thumb/The_Nightmare.png/250px-The_Nightmare.png?0128a",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 67,
        "Name": "Any Zamorak weapon (from Kril Tsutsaroth)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Zamorakian_spear_detail.png/150px-Zamorakian_spear_detail.png?29623",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 68,
        "Name": "(10) Awakener's Orbs OR any Virtus Piece",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Awakener%27s_orb_detail.png/130px-Awakener%27s_orb_detail.png?fb7a8",
        "CompletionCounter": 10,
        "Challenge": "",
    },
    {
        "Number": 69,
        "Name": "150 8-man deathless TOA with all members in Kitty/bingo",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Ba-Ba.png/280px-Ba-Ba.png?648d9",
        "CompletionCounter": 1,
        "Challenge": "GM time with all members in Kitty/bingo",
    },
    {
        "Number": 70,
        "Name": "Dark bow",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Dark_bow_detail.png/150px-Dark_bow_detail.png?71f6b",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 71,
        "Name": "Any (2) TOB purples",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Justiciar_faceguard_detail.png/140px-Justiciar_faceguard_detail.png?b297a",
        "CompletionCounter": 2,
        "Challenge": "",
    },
    {
        "Number": 72,
        "Name": "Any Nex unique (not nihil shards)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Torva_full_helm_%28damaged%29_detail.png/130px-Torva_full_helm_%28damaged%29_detail.png?ecb1b",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 73,
        "Name": "(2) Quivers",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Dizana%27s_quiver_%28uncharged%29_detail.png/150px-Dizana%27s_quiver_%28uncharged%29_detail.png?f6c23",
        "CompletionCounter": 2,
        "Challenge": "",
    },
    {
        "Number": 74,
        "Name": "Any (2) seeds from The Gauntlet",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Crystal_armour_seed_detail.png/120px-Crystal_armour_seed_detail.png?fa149",
        "CompletionCounter": 2,
        "Challenge": "",
    },
    {
        "Number": 75,
        "Name": "(3) Blood Shards",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Blood_shard_detail.png/100px-Blood_shard_detail.png?2fbc7",
        "CompletionCounter": 3,
        "Challenge": "",
    },
    {
        "Number": 76,
        "Name": "Any (3) Zulrah uniques or a mutagen (no scales/scrolls)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Tanzanite_fang_detail.png/170px-Tanzanite_fang_detail.png?859ba",
        "CompletionCounter": 3,
        "Challenge": "",
    },
    {
        "Number": 77,
        "Name": "Budget setup CA",
        "Image": "https://oldschool.runescape.wiki/images/thumb/TzKal-Zuk.png/270px-TzKal-Zuk.png?2d222",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 78,
        "Name": "Phantom Muspah Manipulator CA",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Phantom_Muspah_%28ranged%29.png/250px-Phantom_Muspah_%28ranged%29.png?9cf6a",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 79,
        "Name": "CONNECTION LOST. GO BACK TO TILE 73",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Dying_animation.gif/230px-Dying_animation.gif?30e7c",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 80,
        "Name": "Feather Hunter CA",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Kree%27arra.png/280px-Kree%27arra.png?ba75c",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 81,
        "Name": "Egniol diet 2 CA",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Crystalline_Hunllef.png/280px-Crystalline_Hunllef.png?7737a",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 82,
        "Name": "No time for a drink CA",
        "Image": "https://oldschool.runescape.wiki/images/thumb/TzTok-Jad.png/280px-TzTok-Jad.png?87507",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 83,
        "Name": "Any (2) COX purples (no scrolls)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Ancestral_hat_detail.png/130px-Ancestral_hat_detail.png?b438f",
        "CompletionCounter": 2,
        "Challenge": "",
    },
    {
        "Number": 84,
        "Name": "LOTR (All 4 DKS rings)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Berserker_ring_detail.png/150px-Berserker_ring_detail.png?81f8b",
        "CompletionCounter": 4,
        "Challenge": "",
    },
    {
        "Number": 85,
        "Name": "(10) Ancient Icons OR (5) Venator Shards",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Ancient_icon_detail.png/130px-Ancient_icon_detail.png?137e5",
        "CompletionCounter": 10,
        "Challenge": "",
    },
    {
        "Number": 86,
        "Name": "Any 2 TOB purples (not avernic)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Sanguinesti_staff_detail.png/180px-Sanguinesti_staff_detail.png?aae2c",
        "CompletionCounter": 2,
        "Challenge": "",
    },
    {
        "Number": 87,
        "Name": "(5) Master clue uniques (not shared rewards log)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Clue_scroll_%28master%29_detail.png/150px-Clue_scroll_%28master%29_detail.png?f3c22",
        "CompletionCounter": 5,
        "Challenge": "",
    },
    {
        "Number": 88,
        "Name": "Any Zalcano unique",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Zalcano_shard_detail.png/150px-Zalcano_shard_detail.png?f52af",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 89,
        "Name": "Any (2) TOA purples (not lightbearer/fang)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Masori_body_detail.png/150px-Masori_body_detail.png?3576d",
        "CompletionCounter": 2,
        "Challenge": "",
    },
    {
        "Number": 90,
        "Name": "Complete a full Voidwaker from scratch (1 of each piece) OR Callisto Cub, Venenatis Spiderling, Vet'ion Jr Pet",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Voidwaker_detail.png/150px-Voidwaker_detail.png?01835",
        "CompletionCounter": 3,
        "Challenge": "",
    },
    {
        "Number": 91,
        "Name": "(5) 5 Crystal Armor Seeds OR Enhanced Crystal Weapon Seed",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Crystal_armour_seed_detail.png/140px-Crystal_armour_seed_detail.png?fa149",
        "CompletionCounter": 5,
        "Challenge": "",
    },
    {
        "Number": 92,
        "Name": "Any (3) COX prayer scrolls (not torn)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Dexterous_prayer_scroll_detail.png/150px-Dexterous_prayer_scroll_detail.png?d6a6b",
        "CompletionCounter": 3,
        "Challenge": "",
    },
    {
        "Number": 93,
        "Name": "(3) Chromium Ingots OR any Soulreaper Axe Piece",
        "Image": "",
        "CompletionCounter": 3,
        "Challenge": "Receive any Vestige",
    },
    {
        "Number": 94,
        "Name": "(5) Elite Clue uniques (not shared treasure log)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Clue_scroll_%28elite%29_detail.png/150px-Clue_scroll_%28elite%29_detail.png?87067",
        "CompletionCounter": 5,
        "Challenge": "",
    },
    {
        "Number": 95,
        "Name": "Complete a godsword from scratch (Hilt + 1 of each godsword shard) OR GWD Pet",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Zamorak_godsword_detail.png/140px-Zamorak_godsword_detail.png?f52af",
        "CompletionCounter": 4,
        "Challenge": "",
    },
    {
        "Number": 96,
        "Name": "Any (3) lightbearers or Fangs",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Lightbearer_detail.png/120px-Lightbearer_detail.png?3576d",
        "CompletionCounter": 3,
        "Challenge": "",
    },
    {
        "Number": 97,
        "Name": "Any Jar",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Jar_of_sand_detail.png/90px-Jar_of_sand_detail.png?f533d",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 98,
        "Name": "CM kit or dust",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Twisted_ancestral_colour_kit_detail.png/170px-Twisted_ancestral_colour_kit_detail.png?d72c4",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 99,
        "Name": "HMT kit or dust",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Holy_ornament_kit_detail.png/150px-Holy_ornament_kit_detail.png?17b1d",
        "CompletionCounter": 1,
        "Challenge": "",
    },
    {
        "Number": 100,
        "Name": "(5) Echo Crystals OR Tonalztics of Ralos (MUST BE COMPLETED TO WIN)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Tonalztics_of_ralos_detail.png/150px-Tonalztics_of_ralos_detail.png?10ae1",
        "CompletionCounter": 5,
        "Challenge": "",
    },
]
