BINGO_TILES = [
    {
        "Number": 0,
        "WikiUrl": "",
        "Name": "The bingo hasn't started yet.",
        "Image": "",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [80, 760],
    },
    {
        "Number": 1,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Broken_zombie_axe",
        "Name": "Broken zombie axe",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Zombie_axe_detail.png/120px-Zombie_axe_detail.png?be691",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [155, 715],
    },
    {
        "Number": 2,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Sulphur_blades",
        "Name": "Sulphur blades",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Sulphur_blades_detail.png/130px-Sulphur_blades_detail.png?f6d50",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [214, 674],
    },
    {
        "Number": 3,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Mint_cake",
        "Name": "Mint cake",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Mint_cake_detail.png/130px-Mint_cake_detail.png?783ac",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [270, 635],
    },
    {
        "Number": 4,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Scurrius%27_spine",
        "Name": "3x Scurius Spines",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Scurrius%27_spine_detail.png/130px-Scurrius%27_spine_detail.png?3f9d8",
        "CompletionCounter": 3,
        "Challenge": "",
        "PieceCoordinate": [330, 606],
    },
    {
        "Number": 5,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Crystal_grail",
        "Name": "Crystal Grail",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Crystal_grail_detail.png/120px-Crystal_grail_detail.png?2315b",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [386, 569],
    },
    {
        "Number": 6,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Enhanced_crystal_teleport_seed",
        "Name": "Enhanced teleport seed",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Enhanced_crystal_teleport_seed_detail.png/120px-Enhanced_crystal_teleport_seed_detail.png?84d93",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [470, 560],
    },
    {
        "Number": 7,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Dragon_pickaxe",
        "Name": "Dragon Pickaxe or D2H",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Dragon_pickaxe_detail.png/140px-Dragon_pickaxe_detail.png?4f4ee",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [560, 563],
    },
    {
        "Number": 8,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Clue_scroll_(easy)",
        "Name": "5x Easy clue uniques (Not shared rewards log)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Clue_scroll_%28easy%29_detail.png/150px-Clue_scroll_%28easy%29_detail.png?87067",
        "CompletionCounter": 5,
        "Challenge": "",
        "PieceCoordinate": [620, 575],
    },
    {
        "Number": 9,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Fire_cape",
        "Name": "3x Fire capes",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Fire_cape_detail.png/150px-Fire_cape_detail.png?f1d08",
        "CompletionCounter": 3,
        "Challenge": "",
        "PieceCoordinate": [680, 593],
    },
    {
        "Number": 10,
        "WikiUrl": "",
        "Name": "DON'T IGNORE ME! You think I just made these for fun?! Go back to tile 4.",
        "Image": "https://i.imgur.com/9gkiVW6.png",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [743, 618],
    },
    {
        "Number": 11,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Wintertodt#Rewards",
        "Name": "Wintertodt unique. (No burnt pages)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Phoenix_%28follower%29.png/250px-Phoenix_%28follower%29.png?f6800",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [802, 646],
    },
    {
        "Number": 12,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Perilous_Moons",
        "Name": "Any 4x Perilous Moon equipment pieces (1 for each slot) (please wait for a full completion before using /submit)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Eclipse_atlatl_detail.png/130px-Eclipse_atlatl_detail.png?8f887",
        "CompletionCounter": 4,
        "Challenge": "",
        "PieceCoordinate": [858, 672],
    },
    {
        "Number": 13,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Skills#Skill_types",
        "Name": "1M exp in a gathering skill (not farming)",
        "Image": "https://oldschool.runescape.wiki/images/Stats_icon.png?1b467",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [924, 697],
    },
    {
        "Number": 14,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Blood_shard",
        "Name": "Blood Shard",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Blood_shard_detail.png/100px-Blood_shard_detail.png?2fbc7",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [990, 719],
    },
    {
        "Number": 15,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Forestry#Rewards",
        "Name": "Petal garland, Fox whistle or golden egg",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Petal_garland_detail.png/130px-Petal_garland_detail.png?4c134",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1059, 733],
    },
    {
        "Number": 16,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Zombie_champion_scroll",
        "Name": "Zombie champion scroll",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Zombie_champion_scroll_detail.png/150px-Zombie_champion_scroll_detail.png?3964f",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1123, 738],
    },
    {
        "Number": 17,
        "WikiUrl": "",
        "Name": "Take the Quetzin to tile 23!",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Quetzin_%28follower%29.png/280px-Quetzin_%28follower%29.png?ca338",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [0, 0],
    },
    {
        "Number": 18,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Tempoross",
        "Name": "Any tempeross unique. (25x Soaked pages count. No Spirit flakes/normal roll pages)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Tempoross.png/300px-Tempoross.png?12042",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1250, 744],
    },
    {
        "Number": 19,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Shaman_mask",
        "Name": "Shaman Mask",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Shaman_mask_detail.png/200px-Shaman_mask_detail.png?c8823",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1320, 738],
    },
    {
        "Number": 20,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Kbd_heads",
        "Name": "3x KBD Heads",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Kbd_heads_detail.png/130px-Kbd_heads_detail.png?a6345",
        "CompletionCounter": 3,
        "Challenge": "",
        "PieceCoordinate": [1378, 716],
    },
    {
        "Number": 21,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Barrows#Rewards",
        "Name": "Any 4x Barrows equipment pieces for each armor slot (Please wait for a whole set before using /submit)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Dharok%27s_armour_equipped_male.png/150px-Dharok%27s_armour_equipped_male.png?3d05c",
        "CompletionCounter": 4,
        "Challenge": "Complete a full set from 1 brother",
        "PieceCoordinate": [1386, 680],
    },
    {
        "Number": 22,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Elder_Chaos_druid",
        "Name": "Any 2x Elder chaos robe pieces",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Elder_chaos_top_detail.png/180px-Elder_chaos_top_detail.png?19a96",
        "CompletionCounter": 2,
        "Challenge": "",
        "PieceCoordinate": [1386, 631],
    },
    {
        "Number": 23,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Guardians_of_the_Rift#Rewards",
        "Name": "Any Dye, Lantern, or pet from GOTR",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Abyssal_lantern_%28purple_logs%29_detail.png/150px-Abyssal_lantern_%28purple_logs%29_detail.png?9a479",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1360, 546],
    },
    {
        "Number": 24,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Big_bass",
        "Name": "Any big fish",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Big_shark_detail.png/130px-Big_shark_detail.png?e3794",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1290, 550],
    },
    {
        "Number": 25,
        "WikiUrl": "https://oldschool.runescape.wiki/w/The_Gauntlet",
        "Name": "Any seed from The Gauntlet",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Crystal_weapon_seed_detail.png/130px-Crystal_weapon_seed_detail.png?85ac9",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1222, 550],
    },
    {
        "Number": 26,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Blood_shard",
        "Name": "Blood Shard",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Blood_shard_detail.png/100px-Blood_shard_detail.png?2fbc7",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1148, 572],
    },
    {
        "Number": 27,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Revenants",
        "Name": "Any Rev emblem 2M+ or weapon roll. (avarice, mace, sceptre, bow)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Ancient_medallion_detail.png/150px-Ancient_medallion_detail.png?f448f",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1088, 643],
    },
    {
        "Number": 28,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Theatre_of_Blood#Rewards",
        "Name": "Any TOB Purple",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Monumental_chest_%28player%27s_unique%2C_closed%29.png/280px-Monumental_chest_%28player%27s_unique%2C_closed%29.png?02929",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1022, 647],
    },
    {
        "Number": 29,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Kq_head",
        "Name": "KQ Head",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Kq_head_detail.png/120px-Kq_head_detail.png?4a8ca",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [949, 641],
    },
    {
        "Number": 30,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Golden_tench",
        "Name": "Golden Tench",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Golden_tench_detail.png/130px-Golden_tench_detail.png?27700",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [882, 618],
    },
    {
        "Number": 31,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Pharaoh%27s_sceptre",
        "Name": "Pharaohs sceptre",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Pharaoh%27s_sceptre_%28uncharged%29_detail.png/150px-Pharaoh%27s_sceptre_%28uncharged%29_detail.png?e35e8",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [841, 560],
    },
    {
        "Number": 32,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Medium_clue_scroll",
        "Name": "5x Medium clue uniques (not shared rewards log)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Clue_scroll_%28medium%29_detail.png/150px-Clue_scroll_%28medium%29_detail.png?87067",
        "CompletionCounter": 5,
        "Challenge": "",
        "PieceCoordinate": [860, 501],
    },
    {
        "Number": 33,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Kraken_tentacle",
        "Name": "Kraken tentacle",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Kraken_tentacle_detail.png/130px-Kraken_tentacle_detail.png?e5f2a",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [858, 450],
    },
    {
        "Number": 34,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Malediction_ward",
        "Name": "Complete a wildy ward from scratch (1 of each piece to the same ward)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Malediction_shard_2_detail.png/150px-Malediction_shard_2_detail.png?fe68e",
        "CompletionCounter": 3,
        "Challenge": "",
        "PieceCoordinate": [930, 430],
    },
    {
        "Number": 35,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Tombs_of_Amascut#Rewards",
        "Name": "Any TOA unique (Gems/Thread included)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Chest_%28Tombs_of_Amascut%2C_open%29.png/250px-Chest_%28Tombs_of_Amascut%2C_open%29.png?a0d1e",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [991, 424],
    },
    {
        "Number": 36,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Guild_hunter_outfit",
        "Name": "Any Guild hunter armor piece, huntsman kit, or quetzal pet",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Guild_hunter_top_detail.png/130px-Guild_hunter_top_detail.png?be5ad",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1055, 414],
    },
    {
        "Number": 37,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Venator_shard",
        "Name": "2x Venator shards",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Venator_shard_detail.png/130px-Venator_shard_detail.png?3ad3e",
        "CompletionCounter": 2,
        "Challenge": "",
        "PieceCoordinate": [1118, 422],
    },
    {
        "Number": 38,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Strange_old_lockpick",
        "Name": "Strange old lockpick",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Strange_old_lockpick_%28full%29_detail.png/120px-Strange_old_lockpick_%28full%29_detail.png?1925a",
        "CompletionCounter": 1,
        "Challenge": "Ring of Endurance",
        "PieceCoordinate": [1182, 425],
    },
    {
        "Number": 39,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Curved_bone",
        "Name": "Curved bone",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Curved_bone_detail.png/180px-Curved_bone_detail.png?2315b",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1240, 418],
    },
    {
        "Number": 40,
        "WikiUrl": "",
        "Name": "Take the fairy ring to tile 47!",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Fairy_ring.png/200px-Fairy_ring.png?2ebb4",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [0, 0],
    },
    {
        "Number": 41,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Mask_of_ranul",
        "Name": "Mask of Ranul",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Mask_of_ranul_detail.png/150px-Mask_of_ranul_detail.png?4f67e",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1300, 350],
    },
    {
        "Number": 42,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Dragon_pickaxe",
        "Name": "Any 2x Dragon pickaxes or D2H",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Dragon_2h_sword_detail.png/120px-Dragon_2h_sword_detail.png?6ed9d",
        "CompletionCounter": 2,
        "Challenge": "",
        "PieceCoordinate": [1350, 295],
    },
    {
        "Number": 43,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Skills#Skill_types",
        "Name": "2M exp in a buyable skill",
        "Image": "https://oldschool.runescape.wiki/images/Stats_icon.png?1b467",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1300, 240],
    },
    {
        "Number": 44,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Chambers_of_Xeric#Rewards",
        "Name": "Any COX purple",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Arcane_prayer_scroll_detail.png/160px-Arcane_prayer_scroll_detail.png?54108",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1220, 213],
    },
    {
        "Number": 45,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Vorkath%27s_head",
        "Name": "3x Vorkath Heads",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Vorkath%27s_head_detail.png/130px-Vorkath%27s_head_detail.png?d5b97",
        "CompletionCounter": 3,
        "Challenge": "Dragonbone necklace",
        "PieceCoordinate": [1150, 212],
    },
    {
        "Number": 46,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Unsired",
        "Name": "2x Unsireds",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Unsired_detail.png/200px-Unsired_detail.png?36d00",
        "CompletionCounter": 2,
        "Challenge": "",
        "PieceCoordinate": [1086, 214],
    },
    {
        "Number": 47,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Amulet_of_eternal_glory",
        "Name": "Amulet of Eternal Glory",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Amulet_of_eternal_glory_detail.png/120px-Amulet_of_eternal_glory_detail.png?34ecf",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1024, 217],
    },
    {
        "Number": 48,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Sunfire_fanatic_armour_set",
        "Name": "Any Sunfire fanatic armor piece",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Sunfire_fanatic_helm_detail.png/150px-Sunfire_fanatic_helm_detail.png?b8ba8",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [960, 230],
    },
    {
        "Number": 49,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Last_Man_Standing",
        "Name": "Win 5x games of LMS",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Last_Man_Standing_logo.png/100px-Last_Man_Standing_logo.png?1e913",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [900, 246],
    },
    {
        "Number": 50,
        "WikiUrl": "https://oldschool.runescape.wiki/w/General_Graardor",
        "Name": "Bandos Armor piece",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Bandos_chestplate_detail.png/100px-Bandos_chestplate_detail.png?98028",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [850, 266],
    },
    {
        "Number": 51,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Nex",
        "Name": "Any Nex Unique (not shards)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Zaryte_vambraces_detail.png/130px-Zaryte_vambraces_detail.png?fdfe1",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [800, 296],
    },
    {
        "Number": 52,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Tombs_of_Amascut",
        "Name": "Deathless 500 TOA",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Cursed_phalanx_detail.png/150px-Cursed_phalanx_detail.png?8957f",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [772, 322],
    },
    {
        "Number": 53,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Cerberus",
        "Name": "2x Cerberus Crystals",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Primordial_crystal_detail.png/140px-Primordial_crystal_detail.png?9c62f",
        "CompletionCounter": 2,
        "Challenge": "",
        "PieceCoordinate": [730, 350],
    },
    {
        "Number": 54,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Armadyl",
        "Name": "Any Armadyl Armor piece",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Armadyl_chestplate_detail.png/100px-Armadyl_chestplate_detail.png?78ba5",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [685, 372],
    },
    {
        "Number": 55,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Tombs_of_Amascut",
        "Name": "2x TOA purples",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Osmumten%27s_fang_detail.png/150px-Osmumten%27s_fang_detail.png?b88ec",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [640, 396],
    },
    {
        "Number": 56,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Hard_clue",
        "Name": "5x Hard clue uniques (not shared rewards log)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Clue_scroll_%28hard%29_detail.png/150px-Clue_scroll_%28hard%29_detail.png?11ee4",
        "CompletionCounter": 5,
        "Challenge": "",
        "PieceCoordinate": [587, 417],
    },
    {
        "Number": 57,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Infernal_cape",
        "Name": "Infernal cape",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Infernal_cape_detail.png/150px-Infernal_cape_detail.png?03de7",
        "CompletionCounter": 1,
        "Challenge": "No dig + speedrunner CA in one run",
        "PieceCoordinate": [530, 425],
    },
    {
        "Number": 58,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Nightmare",
        "Name": "Any NM unique (not slepey tablet)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Parasitic_egg_detail.png/100px-Parasitic_egg_detail.png?e786a",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [472, 426],
    },
    {
        "Number": 59,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Commander_Zilyana",
        "Name": "Any Saradomin weapon (from Commander Zilyana)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Saradomin_sword_detail.png/140px-Saradomin_sword_detail.png?5539e",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [415, 430],
    },
    {
        "Number": 60,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Occult_necklace",
        "Name": "Occult Necklace",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Occult_necklace_detail.png/125px-Occult_necklace_detail.png?08adc",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [355, 430],
    },
    {
        "Number": 61,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Facing_Jad_Head-on_IV",
        "Name": "Melee 4 jads CA",
        "Image": "https://oldschool.runescape.wiki/images/thumb/JalTok-Jad.png/280px-JalTok-Jad.png?7e369",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [295, 435],
    },
    {
        "Number": 62,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Chambers_of_Xeric#Rewards",
        "Name": "2x COX purples",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Twisted_buckler_detail.png/130px-Twisted_buckler_detail.png?75ade",
        "CompletionCounter": 2,
        "Challenge": "",
        "PieceCoordinate": [240, 430],
    },
    {
        "Number": 63,
        "WikiUrl": "",
        "Name": "Take the hot air balloon to tile 69!",
        "Image": "https://i.imgur.com/K36EiMd.png",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [0, 0],
    },
    {
        "Number": 64,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Hydra",
        "Name": "Any 2x Hydra pre-rolls",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Hydra%27s_eye_detail.png/130px-Hydra%27s_eye_detail.png?6adc5",
        "CompletionCounter": 2,
        "Challenge": "",
        "PieceCoordinate": [125, 387],
    },
    {
        "Number": 65,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Spirit_shield",
        "Name": "3x Spirit Shields OR Holy Elixir",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Spirit_shield_detail.png/120px-Spirit_shield_detail.png?3524f",
        "CompletionCounter": 3,
        "Challenge": "",
        "PieceCoordinate": [157, 318],
    },
    {
        "Number": 66,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Nightmare",
        "Name": "4:00 NM speed as all members in Kitty/bingo",
        "Image": "https://oldschool.runescape.wiki/images/thumb/The_Nightmare.png/250px-The_Nightmare.png?0128a",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [220, 294],
    },
    {
        "Number": 67,
        "WikiUrl": "https://oldschool.runescape.wiki/w/K%27ril_Tsutsaroth",
        "Name": "Any Zamorak weapon (from Kril Tsutsaroth)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Zamorakian_spear_detail.png/150px-Zamorakian_spear_detail.png?29623",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [283, 291],
    },
    {
        "Number": 68,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Awakener%27s_orb",
        "Name": "10x Awakener's Orbs OR any Virtus Piece",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Awakener%27s_orb_detail.png/130px-Awakener%27s_orb_detail.png?fb7a8",
        "CompletionCounter": 10,
        "Challenge": "",
        "PieceCoordinate": [343, 282],
    },
    {
        "Number": 69,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Tombs_of_Amascut",
        "Name": "150 8-man deathless TOA with all members in Kitty/bingo",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Ba-Ba.png/280px-Ba-Ba.png?648d9",
        "CompletionCounter": 1,
        "Challenge": "GM time with all members in Kitty/bingo",
        "PieceCoordinate": [395, 274],
    },
    {
        "Number": 70,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Dark_bow",
        "Name": "Dark bow",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Dark_bow_detail.png/150px-Dark_bow_detail.png?71f6b",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [433, 254],
    },
    {
        "Number": 71,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Theatre_of_Blood",
        "Name": "Any 2x TOB purples",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Justiciar_faceguard_detail.png/140px-Justiciar_faceguard_detail.png?b297a",
        "CompletionCounter": 2,
        "Challenge": "",
        "PieceCoordinate": [500, 225],
    },
    {
        "Number": 72,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Nex",
        "Name": "Any Nex unique (not nihil shards)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Torva_full_helm_%28damaged%29_detail.png/130px-Torva_full_helm_%28damaged%29_detail.png?ecb1b",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [0, 0],
    },
    {
        "Number": 73,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Quiver",
        "Name": "2x Quivers",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Dizana%27s_quiver_%28uncharged%29_detail.png/150px-Dizana%27s_quiver_%28uncharged%29_detail.png?f6c23",
        "CompletionCounter": 2,
        "Challenge": "",
        "PieceCoordinate": [400, 145],
    },
    {
        "Number": 74,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Gauntlet",
        "Name": "Any 2x seeds from The Gauntlet",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Crystal_armour_seed_detail.png/120px-Crystal_armour_seed_detail.png?fa149",
        "CompletionCounter": 2,
        "Challenge": "",
        "PieceCoordinate": [340, 144],
    },
    {
        "Number": 75,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Blood_shard",
        "Name": "3x Blood Shards",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Blood_shard_detail.png/100px-Blood_shard_detail.png?2fbc7",
        "CompletionCounter": 3,
        "Challenge": "",
        "PieceCoordinate": [293, 144],
    },
    {
        "Number": 76,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Zulrah",
        "Name": "Any 3x Zulrah uniques or a mutagen (no scales/scrolls)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Tanzanite_fang_detail.png/170px-Tanzanite_fang_detail.png?859ba",
        "CompletionCounter": 3,
        "Challenge": "",
        "PieceCoordinate": [225, 185],
    },
    {
        "Number": 77,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Budget_Setup",
        "Name": "Budget setup CA",
        "Image": "https://oldschool.runescape.wiki/images/thumb/TzKal-Zuk.png/270px-TzKal-Zuk.png?2d222",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [194, 134],
    },
    {
        "Number": 78,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Phantom_Muspah_Manipulator",
        "Name": "Phantom Muspah Manipulator CA",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Phantom_Muspah_%28ranged%29.png/250px-Phantom_Muspah_%28ranged%29.png?9cf6a",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [210, 83],
    },
    {
        "Number": 79,
        "WikiUrl": "",
        "Name": "GO BACK TO TILE 73",
        "Image": "https://i.imgur.com/f7QYQki.png",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [0, 0],
    },
    {
        "Number": 80,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Feather_Hunter",
        "Name": "Feather Hunter CA",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Kree%27arra.png/280px-Kree%27arra.png?ba75c",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [319, 57],
    },
    {
        "Number": 81,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Egniol_Diet_II",
        "Name": "Egniol diet 2 CA",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Crystalline_Hunllef.png/280px-Crystalline_Hunllef.png?7737a",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [337, 0],
    },
    {
        "Number": 82,
        "WikiUrl": "https://oldschool.runescape.wiki/w/No_Time_for_a_Drink",
        "Name": "No time for a drink CA",
        "Image": "https://oldschool.runescape.wiki/images/thumb/TzTok-Jad.png/280px-TzTok-Jad.png?87507",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [400, 0],
    },
    {
        "Number": 83,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Chambers_of_Xeric#Rewards",
        "Name": "Any 2x COX purples (no scrolls)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Ancestral_hat_detail.png/130px-Ancestral_hat_detail.png?b438f",
        "CompletionCounter": 2,
        "Challenge": "",
        "PieceCoordinate": [457, 2],
    },
    {
        "Number": 84,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Dagannoth_Kings",
        "Name": "LOTR (All 4 DKS rings)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Berserker_ring_detail.png/150px-Berserker_ring_detail.png?81f8b",
        "CompletionCounter": 4,
        "Challenge": "",
        "PieceCoordinate": [510, 10],
    },
    {
        "Number": 85,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Muspah",
        "Name": "10x Ancient Icons OR 5x Venator Shards",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Ancient_icon_detail.png/130px-Ancient_icon_detail.png?137e5",
        "CompletionCounter": 10,
        "Challenge": "",
        "PieceCoordinate": [565, 15],
    },
    {
        "Number": 86,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Theatre_of_Blood",
        "Name": "Any 2 TOB purples (not avernic)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Sanguinesti_staff_detail.png/180px-Sanguinesti_staff_detail.png?aae2c",
        "CompletionCounter": 2,
        "Challenge": "",
        "PieceCoordinate": [614, 30],
    },
    {
        "Number": 87,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Master_clue",
        "Name": "5x Master clue uniques (not shared rewards log)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Clue_scroll_%28master%29_detail.png/150px-Clue_scroll_%28master%29_detail.png?f3c22",
        "CompletionCounter": 5,
        "Challenge": "",
        "PieceCoordinate": [673, 50],
    },
    {
        "Number": 88,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Zalcano",
        "Name": "Any Zalcano unique",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Zalcano_shard_detail.png/150px-Zalcano_shard_detail.png?f52af",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [725, 77],
    },
    {
        "Number": 89,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Tombs_of_Amascut",
        "Name": "Any 2x TOA purples (not lightbearer/fang)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Masori_body_detail.png/150px-Masori_body_detail.png?3576d",
        "CompletionCounter": 2,
        "Challenge": "",
        "PieceCoordinate": [773, 95],
    },
    {
        "Number": 90,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Voidwaker",
        "Name": "Complete a full Voidwaker from scratch (1 of each piece) OR Callisto Cub, Venenatis Spiderling, Vet'ion Jr Pet",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Voidwaker_detail.png/150px-Voidwaker_detail.png?01835",
        "CompletionCounter": 3,
        "Challenge": "",
        "PieceCoordinate": [819, 107],
    },
    {
        "Number": 91,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Gauntlet",
        "Name": "5x Crystal Armor Seeds OR Enhanced Crystal Weapon Seed",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Crystal_armour_seed_detail.png/140px-Crystal_armour_seed_detail.png?fa149",
        "CompletionCounter": 5,
        "Challenge": "",
        "PieceCoordinate": [865, 117],
    },
    {
        "Number": 92,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Chambers_of_Xeric#Rewards",
        "Name": "Any 3x COX prayer scrolls (not torn)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Dexterous_prayer_scroll_detail.png/150px-Dexterous_prayer_scroll_detail.png?d6a6b",
        "CompletionCounter": 3,
        "Challenge": "",
        "PieceCoordinate": [900, 130],
    },
    {
        "Number": 93,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Chromium_ingot",
        "Name": "3x Chromium Ingots OR any Soulreaper Axe Piece",
        "Image": "",
        "CompletionCounter": 3,
        "Challenge": "Receive any Vestige",
        "PieceCoordinate": [950, 130],
    },
    {
        "Number": 94,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Elite_clue",
        "Name": "5x Elite Clue uniques (not shared treasure log)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Clue_scroll_%28elite%29_detail.png/150px-Clue_scroll_%28elite%29_detail.png?87067",
        "CompletionCounter": 5,
        "Challenge": "",
        "PieceCoordinate": [998, 119],
    },
    {
        "Number": 95,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Godsword",
        "Name": "Complete a godsword from scratch (Hilt + 1 of each godsword shard) OR GWD Pet",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Zamorak_godsword_detail.png/140px-Zamorak_godsword_detail.png?f52af",
        "CompletionCounter": 4,
        "Challenge": "",
        "PieceCoordinate": [1045, 110],
    },
    {
        "Number": 96,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Tombs_of_Amascut",
        "Name": "Any 3x Lightbearers or Fangs",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Lightbearer_detail.png/120px-Lightbearer_detail.png?3576d",
        "CompletionCounter": 3,
        "Challenge": "",
        "PieceCoordinate": [1097, 99],
    },
    {
        "Number": 97,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Jar",
        "Name": "Any Jar",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Jar_of_sand_detail.png/90px-Jar_of_sand_detail.png?f533d",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1150, 90],
    },
    {
        "Number": 98,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Challenge_mode",
        "Name": "CM kit or dust",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Twisted_ancestral_colour_kit_detail.png/170px-Twisted_ancestral_colour_kit_detail.png?d72c4",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1203, 81],
    },
    {
        "Number": 99,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Theatre_of_Blood/Hard_Mode",
        "Name": "HMT kit or dust",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Holy_ornament_kit_detail.png/150px-Holy_ornament_kit_detail.png?17b1d",
        "CompletionCounter": 1,
        "Challenge": "",
        "PieceCoordinate": [1258, 74],
    },
    {
        "Number": 100,
        "WikiUrl": "https://oldschool.runescape.wiki/w/Tonalztics_of_ralos",
        "Name": "5x Echo Crystals OR Tonalztics of Ralos (MUST BE COMPLETED TO WIN)",
        "Image": "https://oldschool.runescape.wiki/images/thumb/Tonalztics_of_ralos_detail.png/150px-Tonalztics_of_ralos_detail.png?10ae1",
        "CompletionCounter": 5,
        "Challenge": "",
        "PieceCoordinate": [1323, 70],
    },
]
